services:
  db:
    container_name: beer-review-db
    restart: always
    ports:
      - 5432:5432
    volumes:
     - ./db_data:/var/lib/postgresql/
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: beer_review
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  dataserver:
    container_name: beer-review-dataserver
    restart: always
    ports:
      - 8000:8000
    build:
      context: ./beer-review-dataserver/
    volumes:
     - ./images:/images
    environment:
      WATCHFILES_FORCE_POLLING: true
      host: "0.0.0.0"
      port: 8000
      log_level: info
      postgres_uri: postgresql+asyncpg://postgres:postgres@db:5432/beer_review
      image_dir: /images
    develop:
      watch:
        - action: sync
          path: ./beer-review-dataserver/
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./beer-review-dataserver/pyproject.toml
    depends_on:
      - db

  website:
    container_name: beer-review-website
    restart: always
    ports:
      - "3000:3000"
    build:
      context: ./beer-review-website/
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=http://dataserver:8000
    develop:
      watch: 
      - action: sync
        path: ./beer-review-website/
        target: /app
        ignore: node_modules/
      - action: rebuild
        path: package.json
      - action: rebuild
        path: pnpm-lock.json
    depends_on:
      - dataserver

networks:
  beer-review-network:
    external: true